# Review of Python Basics

Original tutorial developed by DePaul University (CSC 478) - revised by Dr. Jie Tao.

## Basic Calculations

Basic arithmetic calculations:

In [1]:
# Algebra: add (+), subtract (-), multiply (*), divide (/)
# PEMDAS order

x = 1 + 2 * 3
x

7

Other calculations:

In [2]:
# Exponents use **
# 2 to the 3rd power

y = 2 ** 3
y

8

Logic Calculation:

In [3]:
# Double equal checks for equality
# Single equal defines a variable

x == y

False

String Calculation:

In [4]:
# Define string with =
# Make sure to use ' ' for strings
# Addition will put the strings together eliminating spaces

my_str = 'Fairfield' + 'University'
print(my_str)

FairfieldUniversity


In [5]:
# .upper() capitalizes all the letters in a defined string

my_str.upper()

'FAIRFIELDUNIVERSITY'

In [6]:
# .upper() lowercases all the letters in a defined string

my_str.lower()

'fairfielduniversity'

In [7]:
# Just prints the string

my_str

'FairfieldUniversity'

Notice that upper() and lower() are methods - they do not change the variable value.

In [8]:
# 'len()' finds the length
# 19 letters in 'my_str'

len(my_str)

19

## Data Types

In [9]:
# Define variables and add them into other functions 
# '[]' creates a list
# This prints the results of a b and c

a = 2 + 3
b = a * 4
c = b - 7
L = [a,b,c]
print(L)

[5, 20, 13]


In [10]:
# Previous variables can be used in a new equation
    # Make sure to clearly define and remember the variables you have used
# This prints the previous 'L' list plus list 'M'
# Notice 'a' is printed as 'a' because of the quotes making it a string, 
    # not the number associated with a (5)
    
M = [10, 2, "a", 3.5]
N = L + M
print(N)

[5, 20, 13, 10, 2, 'a', 3.5]


In [11]:
# len() finds the length of the list
# There are 7 numbers/letters in list N

len(N)

7

Lists + Dicts:

In [12]:
# This is what a comment looks like 

# LIST:
# fruits list is defined 
# for loop prints the word in the list plus for sale individually
    # "apples for sale"

fruits = ['apples','oranges','pears','bananas']
for fruit in fruits:
    print (fruit + ' for sale')

# DICTIONARY:
# Dictionary = {'key':'value',...} (can use both strings and/or integers)
# fruitPrices links one word/number to another
    # Apples are 2.00.. oranges are 1.50.. pears are 1.75
# for loop if statement:
    # if the price (the value) is less than 2.. 
        # print '"fruit name" cost "price" a pound'
        # %s and %f connect the fruit to the price.. use '%(fruit, price)' at the end
        # notice the for loop begins with 'for fruit, price'
    # else print the price (the value) and add the string 'are too expensive!'

fruitPrices = {'apples': 2.00, 'oranges': 1.50, 'pears': 1.75}
for fruit, price in fruitPrices.items():
    if price < 2.00:
        print ('%s cost %f a pound' % (fruit, price))
    else:
        print (fruit + ' are too expensive!')
        
# Final result will print the first for loop lines followed by the second for loop price comparison

# ** Lists use [] and Dictionaries use {} !!!! **

apples for sale
oranges for sale
pears for sale
bananas for sale
apples are too expensive!
oranges cost 1.500000 a pound
pears cost 1.750000 a pound


In [13]:
# Example of python's list comprehension construction:

# Define a list of numbers as 'nums'
# plusOneNums is a list for statement
    # Add 1 to x.. x is each number in the list 'nums'
# Print 'plusOneNums=' to type the string and plusOneNums to print the true numbers

nums = [1,2,3,4,5,6]
plusOneNums = [x+1 for x in nums]
print ("plusOneNums =", plusOneNums)

# Define new list for odd numbers (oddNums)
    # print x for x (x = a number in 'nums') if divisible by 2 equals 1 (if its odd)
# Print 'oddNums=' to type the string and ',oddNums' to print the true numbers

oddNums = [x for x in nums if x % 2 == 1]
print ("oddNums = ", oddNums)

# Define new list for odd numbers plus 1.. *even numbers*.. (oddNumsPlusOne)
    # add 1 to x (x = a number in 'nums'), then find if x is divisible by 2 equals 1 (if its odd)
# Print 'oddNumsPlusOne=' to type the string and ',oddNumsPlusOne' to print the true numbers

oddNumsPlusOne = [x+1 for x in nums if x % 2 ==1]
print ("oddNumsPlusOne = ", oddNumsPlusOne)

plusOneNums = [2, 3, 4, 5, 6, 7]
oddNums =  [1, 3, 5]
oddNumsPlusOne =  [2, 4, 6]


Dictionaries:

In [14]:
# Dictionaries
# Remember dictionaries use {} (lists use [])

# 'studentIds['turing']' will print the value that goes with the key
    # 'turing' prints the value '56.0'
    # 'knuth' prints the value '42.0'
    # 'nash' prints the value '92.0'

studentIds = {'knuth': 42.0, 'turing': 56.0, 'nash': 92.0 }
studentIds['turing']

56.0

In [15]:
# Add a value and key to a dictionary
# DictionaryName['NewKey'] = Value
# This adds the key 'ada' with the vaue '97.0' to the studentIds dictionary

studentIds['ada'] = 97.0
studentIds

{'knuth': 42.0, 'turing': 56.0, 'nash': 92.0, 'ada': 97.0}

In [16]:
# Delete a value and key in a dictionary
# 'del' is used to delete
# del DictionaryName['KeyName']
    # you dont need the value
# This deleted 'knuth' and the connected key '42' from the dictionary 'studentIds'

del studentIds['knuth']
studentIds

{'turing': 56.0, 'nash': 92.0, 'ada': 97.0}

In [17]:
# A value can be in the form of a list
    # Use [] to add a list to a value
# This makes knuths value a list stating a number and a string 

studentIds['knuth'] = [42.0,'forty-two']
studentIds

{'turing': 56.0, 'nash': 92.0, 'ada': 97.0, 'knuth': [42.0, 'forty-two']}

In [18]:
# Print out just the keys in the dictionary studentIds
# .keys() prints a list of only the keys

studentIds.keys()

dict_keys(['turing', 'nash', 'ada', 'knuth'])

In [19]:
# Print out just the values in the dictionary studentIds
# .values() prints a list of only the values

studentIds.values()

dict_values([56.0, 92.0, 97.0, [42.0, 'forty-two']])

In [20]:
# Print out what is in the dictionary studentIds
# .items() prints a list of the values and keys
# dict_items([('key', value),...])

studentIds.items()

dict_items([('turing', 56.0), ('nash', 92.0), ('ada', 97.0), ('knuth', [42.0, 'forty-two'])])

In [21]:
# Print the length of the dictionary
# studentIds has 4 keys
    # ** Counts a value and a key as 1
len(studentIds) 

4

## Numpy Basics

In [22]:
# "NumPy is a library for the Python programming language, adding support for large, 
# multi-dimensional arrays and matrices, along with a large collection of high-level 
# mathematical functions to operate on these arrays"

import numpy as np

In [23]:
# Creating a 1-d array
# np.array() creates an array of numbers (similar to a list)

my_arr = np.array([1,2,3,4,5])
my_arr

array([1, 2, 3, 4, 5])

In [24]:
# Creating a 1-d array from an existing Python list
# np.array can turn a predefined list into a numpy list

my_lst = [1, 2, 3, 4, 5, 6]

my_arr = np.array(my_lst)
my_arr

array([1, 2, 3, 4, 5, 6])

In [26]:
# Divides each number in the array by 5
# ex: 1/5 = 0.2
my_arr/5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2])

In [28]:
# Multiply a Numpy array by a list
# This example creates a list named "my_res" by multiplying the numbers in my_lst by another_arr
   # 1*2=2, 2*3=6, 3*4=12, 4*5=20, 5*6=30, 6*7=42

another_arr = np.array([2, 3, 4, 5, 6, 7])

my_res = my_lst * another_arr
my_res

array([ 2,  6, 12, 20, 30, 42])

In [30]:
# .sum() adds up all the numbers in an array
    # 2+6+12+20+30+42

my_res.sum()

112

In [32]:
# .mean() finds the mean of the array

my_res.mean()

18.666666666666668

In [34]:
# Dot product of two vectors
    # (1*2 + 2*6 + 3*4 + 4*5 + 5*6 + 6*7) = (2 + 6 + 12 + 20 + 30 + 42) = 112

np.dot(my_lst, another_arr)

112

In [36]:
# Creating a 2-d array
# Multidimensional lists of items that are the same type and same size
    # This makes 3 lists

X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
# Transpose a 2-d array
# .T is used to transpose
    # Transpose flips the lists and creates new lists
    # All the first numbers are now a list, all the second numbers, and all the third numbers

X.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
# Array slicing
    # 0, 1.. middle section
    # 0, 1, 2.. last number in the middle section

X[1,2]

6

In [50]:
# Row 0 (first row).. : = all the numbers

X[0,:]

array([1, 2, 3])

In [54]:
# Start at row 1 (skip row 0), through to the last row
# Numbers 1 to the end
    # Not the first number in the row, the middle and last number in the middle and end list

X[1:,1:]



array([[5, 6],
       [8, 9]])

In [55]:
# Start at row 1 (skip row 0), through to the last row
    # List numbers 0 and 1.. **The 2 does not count!, left number counts, right doesnt**
    # The middle and last number in the middle and last list

X[1:,0:2]

array([[4, 5],
       [7, 8]])

In [57]:
# Using arrays to index into other arrays (e.g., Boolean masks)
# "A > 3" finds compares each number in the list to the boolean 
    # If the number is greater than 3 it will say True, if it is less it will say False
    # 1>3=False, 2>3=False, 3>3=False, 4>3=True, 5>3=True, 6>3=True

A = np.array([1, 2, 3, 4, 5, 6])
A > 3

array([False, False, False,  True,  True,  True])

In [59]:
# This only outputs the numbers that are greater than 3 into a list
    # (Rather than a 'True' and 'False' list)

A[A > 3]

array([4, 5, 6])

In [61]:
# Finds the sum of all the numbers in the list that are greater than 3
    # 4 + 5 + 6 = 15

sum(A[A > 3])

15

In [64]:
# This example creates a new variable 'Ind' that finds all the numbers in the array that are >1 AND <6
# print(Ind) will show a list in true false format
# A[Ind] will show only the numbers from the array the fit the boolean expression

Ind = (A > 1) & (A < 6)
print(Ind)
A[Ind]

[False  True  True  True  True False]


array([2, 3, 4, 5])